### ISSUE TITLE
im not even gonna say it

### ISSUE THREAD

**Issue by ninjialfakerealnottrue** [editorial50/WalmartList#15]
sphere can already tell

**Comment by sphericle** [comment]
template: `
        <div class="level-authors">
            <template v-if="selfVerified">
                <div class="type-title-sm">Creator & Verifier</div>
                <p class="type-body">
                    <span>{{ verifier }}</span>
                </p>
            </template>
            <template v-else-if="creators.length === 1"> 
                <div class="type-title-sm">Creator</div>
                <p class="type-body">
                    <span>{{ creators[0] }}</span> 

  <template v-else> 
                <div class="type-title-sm">Creators</div>
                <p class="type-body">
                    <template v-for="(creator, index) in creators" :key="\`creator-\$\{creator\}\`">
                        <span>{{ creator }}</span>
                        <span v-if="index < creators.length - 1">, </span>
                    </template>

computed: {
        selfVerified() {
            return this.creators.length === 0;

`

**Comment by sphericle** [comment]
template: `
        <div class="level-authors">
            <template v-if="selfVerified">
                <div class="type-title-sm">Creator & Verifier</div>
                <p class="type-body">
                    <span>{{ verifier }}</span>
                </p>
            </template>
            <template v-else-if="creators.length === 1"> 
                <div class="type-title-sm">Creator</div>
                <p class="type-body">
                    <span>{{ creators[0] }}</span> 

  <template v-else> 
                <div class="type-title-sm">Creators</div>
                <p class="type-body">
                    <template v-for="(creator, index) in creators" :key="\`creator-\$\{creator\}\`">
                        <span>{{ creator }}</span>
                        <span v-if="index < creators.length - 1">, </span>
                    </template>

computed: {
        selfVerified() {
            return this.creators.length === 0;

`

**Comment by editorial50** [comment]
crazy stuff bro

**Comment by sphericle** [comment]
template: `
<div class="level-authors">
<template v-if="selfVerified">
<div class="type-title-sm">Creator & Verifier</div>
 <p class="type-body">
 <span>{{ verifier }}</span>
 </p>
 </template>
<template v-else-if="creators.length === 1"> 
 <div class="type-title-sm">Creator</div>
 <p class="type-body">
 <span>{{ creators[0] }}</span> 

  <template v-else> 
  <div class="type-title-sm">Creators</div>
  <p class="type-body">
  <template v-for="(creator, index) in creators" :key="\`creator-\$\{creator\}\`">
  <span>{{ creator }}</span>
 <span v-if="index < creators.length - 1">, </span>
 </template>

computed: {
selfVerified() {
return this.creators.length === 0;

`

**Comment by sphericle** [comment]
`template: `
<div class="level-authors">
<template v-if="selfVerified">
<div class="type-title-sm">Creator & Verifier</div>
 <p class="type-body">
 <span>{{ verifier }}</span>
 </p>
 </template>
<template v-else-if="creators.length === 1"> 
 <div class="type-title-sm">Creator</div>
 <p class="type-body">
 <span>{{ creators[0] }}</span> 

  <template v-else> 
  <div class="type-title-sm">Creators</div>
  <p class="type-body">
  <template v-for="(creator, index) in creators" :key="\`creator-\$\{creator\}\`">
  <span>{{ creator }}</span>
 <span v-if="index < creators.length - 1">, </span>
 </template>

computed: {
selfVerified() {
return this.creators.length === 0;

``

**Comment by sphericle** [comment]
![image](https://github.com/editorial50/WalmartList/assets/86196223/37f0e75a-c0ab-4884-8c1e-15f640841fa6)

**Comment by Ultrobro** [comment]
![image](https://github.com/editorial50/WalmartList/assets/161904065/9b3df9f7-ae7f-4873-a423-b113b434c334)

**Comment by editorial50** [comment]
ninjial 🤮

**Comment by editorial50** [comment]
ninjial 🤮🤮🤮

**Comment by editorial50** [comment]
https://images-ext-1.discordapp.net/external/6OWGK_7aQ-DZ_sQqCoQwdeWCqjaqzGOuit3reym2QoA/https/github.com/editorial50/WalmartList/assets/86196223/f61894f8-5fdb-49a8-add4-b6af8dba4ea3?format=webp

**Comment by editorial50** [comment]
https://images-ext-1.discordapp.net/external/6OWGK_7aQ-DZ_sQqCoQwdeWCqjaqzGOuit3reym2QoA/https/github.com/editorial50/WalmartList/assets/86196223/f61894f8-5fdb-49a8-add4-b6af8dba4ea3?format=webp

**Comment by editorial50** [comment]
ninjial when he realises hes not getting dev 😢
