### ISSUE TITLE
fix the song thing loser

### ISSUE THREAD

**Issue by ninjialfakerealnottrue** [editorial50/WalmartList#17]
![image](https://github.com/editorial50/WalmartList/assets/161901667/b1abaea9-985b-4c12-a884-4a5567d2658f)
this one too 
![image](https://github.com/editorial50/WalmartList/assets/161901667/863d41b7-d7cd-49e1-a6c9-6d001ea87748)

**Comment by ninjialfakerealnottrue** [comment]
im actually so back

**Comment by sphericle** [comment]
bro came back to scanning our site 💀

**Comment by editorial50** [comment]
go outside bro
