### ISSUE TITLE
bro came back to scanning our site 💀

### ISSUE THREAD

**Issue by ninjialfakerealnottrue** [editorial50/WalmartList#18]
bro came back to scanning our site 💀

_Originally posted by @sphericle in https://github.com/editorial50/WalmartList/issues/17#issuecomment-2002215102_

**Comment by ninjialfakerealnottrue** [comment]
found another one 
![image](https://github.com/editorial50/WalmartList/assets/161901667/bf03df33-f55e-491c-83e5-b232d6d8ac10)

**Comment by sphericle** [comment]
we need purpled to upload more, u got too much time on yo hands

**Comment by editorial50** [comment]
go outside

**Comment by ninjialfakerealnottrue** [comment]
i found more :D 7, 8, 10, 12
