### ISSUE TITLE
you guys are buffoons!!!11 fix your website

### ISSUE THREAD

**Issue by ninjialfakerealnottrue** [editorial50/WalmartList#2]
#1 the password is wrong cuz the level is free to copy on walmart acute
#2 the creator thing is plural even though there's 1 creator on all 3 levels
#3 you could also change that to creator&verifier setting (only for wamart acute) cuz it just makes more sense
#4 same password thing but walmart avengance has a password to copy and it says not copyable

**Comment by sphericle** [comment]
mostly fixed
